package com.example.backend.notifications;

public enum NotificationType {
  PROJECT_INVITATION,
  PROJECT_INVITATION_ACCEPTED,
  PROJECT_INVITATION_REJECTED,
  TEAM_INVITATION,
  TEAM_INVITATION_ACCEPTED,
  TEAM_INVITATION_REJECTED,

  TASK_ASSIGNED,
  TASK_STATUS_CHANGED,
}
